import { Professor } from './types/types';

export const PROFESSORES_MOCK: Professor[] = [
  {
    id: 'prof-1',
    nome: 'Ana Beatriz Costa',
    cpf: '123.456.789-10',
    email: 'ana.costa@gymcore.com.br',
    contato: '(85) 99911-2040',
    fotoUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Aldeota' },
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Sul' },
    ],
    modalidades: ['Musculação', 'Treinamento funcional', 'Alongamento'],
  },
  {
    id: 'prof-2',
    nome: 'Carlos Henrique Lima',
    cpf: '234.567.890-21',
    email: 'carlos.lima@gymcore.com.br',
    contato: '(85) 98822-5511',
    fotoUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'Move Studio', unidade: 'Move Studio Meireles' },
    ],
    modalidades: ['Pilates', 'Mobilidade'],
  },
  {
    id: 'prof-3',
    nome: 'Mariana Torres Nunes',
    cpf: '345.678.901-32',
    email: 'mariana.torres@gymcore.com.br',
    contato: '(85) 97733-6248',
    status: 'AFASTADO',
    unidades: [
      { estabelecimento: 'Zenith Wellness', unidade: 'Zenith Wellness Cocó' },
      { estabelecimento: 'Zenith Wellness', unidade: 'Zenith Wellness Beira Mar' },
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Aldeota' },
    ],
    modalidades: ['Yoga', 'Pilates', 'Respiração'],
  },
  {
    id: 'prof-4',
    nome: 'Rafael Moura',
    cpf: '456.789.012-43',
    email: 'rafael.moura@gymcore.com.br',
    contato: '(85) 96644-7802',
    fotoUrl: 'https://images.unsplash.com/photo-1584466977773-e625c37cdd50?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'Iron Box', unidade: 'Iron Box Sul' },
      { estabelecimento: 'Pulse Performance', unidade: 'Pulse Performance Iguatemi' },
    ],
    modalidades: ['Cross training', 'Levantamento olímpico'],
  },
  {
    id: 'prof-5',
    nome: 'Juliana Martins Rocha',
    cpf: '567.890.123-54',
    email: 'juliana.rocha@gymcore.com.br',
    contato: '(85) 95555-3309',
    status: 'INATIVO',
    unidades: [
      { estabelecimento: 'Arena Kids', unidade: 'Arena Kids Parquelandia' },
    ],
    modalidades: ['Natação infantil', 'Recreação esportiva'],
  },
  {
    id: 'prof-6',
    nome: 'Pedro Augusto Vieira',
    cpf: '678.901.234-65',
    email: 'pedro.vieira@gymcore.com.br',
    contato: '(85) 94466-9090',
    fotoUrl: 'https://images.unsplash.com/photo-1571019613914-85f342c6a11e?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'Pulse Performance', unidade: 'Pulse Performance Iguatemi' },
      { estabelecimento: 'Pulse Performance', unidade: 'Pulse Performance Dunas' },
      { estabelecimento: 'Zenith Wellness', unidade: 'Zenith Wellness Cocó' },
    ],
    modalidades: ['Performance', 'Corrida', 'Treinamento funcional', 'Musculação'],
  },
];
