import { Aluno } from './types';

export const ALUNOS_MOCK: Aluno[] = [
  {
    id: 'aluno-1',
    nome: 'Bruno Nogueira',
    cpf: '111.222.333-44',
    email: 'bruno.nogueira@gymcore.com.br',
    contato: '(85) 99920-1100',
    fotoUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Aldeota' },
    ],
    planoAtual: 'Mensal Full',
    modalidades: ['Musculação', 'Funcional'],
    matricula: {
      codigo: 'MAT-001',
      dataInicio: '10/01/2026',
      vencimento: 10,
      status: 'ATIVA',
    },
  },
  {
    id: 'aluno-2',
    nome: 'Larissa Moura',
    cpf: '222.333.444-55',
    email: 'larissa.moura@gymcore.com.br',
    contato: '(85) 98833-2040',
    status: 'PENDENTE',
    unidades: [
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Aldeota' },
      { estabelecimento: 'Move Studio', unidade: 'Move Studio Meireles' },
    ],
    planoAtual: 'Trimestral Performance',
    modalidades: ['Pilates', 'Mobilidade'],
    matricula: {
      codigo: 'MAT-002',
      dataInicio: '05/03/2026',
      vencimento: 15,
      status: 'PENDENTE',
    },
  },
  {
    id: 'aluno-3',
    nome: 'Rafael Martins',
    cpf: '333.444.555-66',
    email: 'rafael.martins@gymcore.com.br',
    contato: '(85) 97744-8811',
    fotoUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Sul' },
    ],
    planoAtual: 'Mensal Basic',
    modalidades: ['Musculação'],
    matricula: {
      codigo: 'MAT-003',
      dataInicio: '22/04/2026',
      vencimento: 5,
      status: 'ATIVA',
    },
  },
  {
    id: 'aluno-4',
    nome: 'Camila Teixeira',
    cpf: '444.555.666-77',
    email: 'camila.teixeira@gymcore.com.br',
    contato: '(85) 96655-3001',
    status: 'INATIVO',
    unidades: [
      { estabelecimento: 'Iron Box', unidade: 'Iron Box Sul' },
    ],
    planoAtual: 'Cross Training Livre',
    modalidades: ['Cross training'],
    matricula: {
      codigo: 'MAT-004',
      dataInicio: '18/11/2025',
      vencimento: 20,
      status: 'ENCERRADA',
    },
  },
  {
    id: 'aluno-5',
    nome: 'Felipe Andrade',
    cpf: '555.666.777-88',
    email: 'felipe.andrade@gymcore.com.br',
    contato: '(85) 95566-7710',
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=180&q=80',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'Move Studio', unidade: 'Move Studio Meireles' },
    ],
    planoAtual: 'Pilates Individual',
    modalidades: ['Pilates'],
    matricula: {
      codigo: 'MAT-005',
      dataInicio: '02/06/2026',
      vencimento: 12,
      status: 'ATIVA',
    },
  },
  {
    id: 'aluno-6',
    nome: 'Renata Alves',
    cpf: '666.777.888-99',
    email: 'renata.alves@gymcore.com.br',
    contato: '(85) 94477-8802',
    status: 'ATIVO',
    unidades: [
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Aldeota' },
      { estabelecimento: 'PowerFit', unidade: 'PowerFit Sul' },
    ],
    planoAtual: 'Mensal Full',
    modalidades: ['Musculação', 'Dança', 'Alongamento'],
    matricula: {
      codigo: 'MAT-006',
      dataInicio: '14/02/2026',
      vencimento: 25,
      status: 'ATIVA',
    },
  },
];
